### ISSUE TITLE
import failed insdie docker-janusgraph image

### ISSUE THREAD

**Issue by tedhtchang** [IBM/janusgraph-utils#26]
winnie got  the exception when doing import inside the docker-janusgraph image 
root@perf-rs-jn7q4-nnjcr:/home/janusgraph/janusgraph-utils# export JANUSGRAPH_HOME=/home/janusgraph/janusgraph ;./run.sh import /home/janusgraph/janusgraph/conf/janusgraph-cql-es.properties /tmp/ /tmp/schema.json  /tmp/datamapper.json 
JanusGraph lib path is set to /home/janusgraph/janusgraph/lib
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/janusgraph/janusgraph/lib/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/janusgraph/janusgraph/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
23:12:00.375 [main] DEBUG o.a.c.c.PropertiesConfiguration - FileName set to janusgraph-cql-es.properties
23:12:00.388 [main] DEBUG o.a.c.c.PropertiesConfiguration - Base path set to /home/janusgraph/janusgraph/conf
23:12:00.396 [main] DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is /home/janusgraph/janusgraph/conf, name is janusgraph-cql-es.properties
23:12:00.396 [main] DEBUG o.a.c.c.DefaultFileSystem - Could not locate file janusgraph-cql-es.properties at /home/janusgraph/janusgraph/conf: no protocol: /home/janusgraph/janusgraph/conf
23:12:00.397 [main] DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the path /home/janusgraph/janusgraph/conf/janusgraph-cql-es.properties
23:12:00.844 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
23:12:00.850 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
23:12:00.870 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
23:12:01.206 [main] INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
23:12:01.218 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 4
23:12:01.340 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster with contact points [/10.45.0.138:9042]
23:12:01.365 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
23:12:01.375 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
23:12:01.375 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
23:12:01.376 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
23:12:01.376 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
23:12:01.378 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
23:12:01.378 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
23:12:01.379 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
23:12:01.379 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
23:12:01.455 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: available
23:12:01.456 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
23:12:01.456 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
23:12:01.456 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
23:12:01.467 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
23:12:01.472 [main] DEBUG i.n.u.internal.NativeLibraryLoader - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
23:12:01.472 [main] DEBUG i.n.u.internal.NativeLibraryLoader - -Dio.netty.netty.workdir: /tmp (io.netty.tmpdir)
23:12:01.477 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
23:12:01.479 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
23:12:01.494 [main] INFO  com.datastax.driver.core.NettyUtil - Found Netty's native epoll transport in the classpath, using it
23:12:01.519 [main] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
23:12:01.541 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetectionLevel: simple
23:12:01.549 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
23:12:01.660 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.45.0.138:9042] preparing to open 1 new connections, total = 1
23:12:01.664 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
23:12:01.672 [main] DEBUG i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.com.datastax.driver.core.Message$ResponseMatcher
23:12:01.700 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
23:12:01.700 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
23:12:01.701 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
23:12:01.701 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
23:12:01.701 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
23:12:01.701 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
23:12:01.701 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
23:12:01.701 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
23:12:01.701 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
23:12:01.701 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:69)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:477)
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:409)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1353)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:107)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:75)
	at com.ibm.janusgraph.utils.importer.BatchImport.main(BatchImport.java:33)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
	... 6 more
Caused by: java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newLongCounter()Lio/netty/util/internal/LongCounter;
	at io.netty.buffer.PoolArena.<init>(PoolArena.java:65)
	at io.netty.buffer.PoolArena$HeapArena.<init>(PoolArena.java:638)
	at io.netty.buffer.PooledByteBufAllocator.<init>(PooledByteBufAllocator.java:179)
	at io.netty.buffer.PooledByteBufAllocator.<init>(PooledByteBufAllocator.java:153)
	at io.netty.buffer.PooledByteBufAllocator.<init>(PooledByteBufAllocator.java:145)
	at io.netty.buffer.PooledByteBufAllocator.<clinit>(PooledByteBufAllocator.java:128)
	at com.datastax.driver.core.NettyOptions.afterBootstrapInitialized(NettyOptions.java:144)
	at com.datastax.driver.core.Connection$Factory.newBootstrap(Connection.java:890)
	at com.datastax.driver.core.Connection$Factory.access$100(Connection.java:740)
	at com.datastax.driver.core.Connection.initAsync(Connection.java:138)
	at com.datastax.driver.core.Connection$Factory.open(Connection.java:796)
	at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:253)
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:201)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1483)
	at com.datastax.driver.core.Cluster.init(Cluster.java:159)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:247)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.initializeSession(CQLStoreManager.java:262)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:146)
	... 11 more
Work around is to load netty-all first. 
Inside run.sh:
java -cp $JANUSGRAPH_HOME/lib/netty-all-4.0.28.Final.jar:"$CP":"${utilityJar}" com.ibm.janusgraph.utils.importer.BatchImport "$@"

**Comment by tedhtchang** [comment]
Winnie can no longer reproduce this issue.
