### ISSUE TITLE
java.text.ParseException: Unparseable date:

### ISSUE THREAD

**Issue by zhaochl** [IBM/janusgraph-utils#68]
I generate the demo by command
`
./run.sh gencsv csv-conf/twitter-like-w-date2.json /tmp/json
`
But error happends
```
java.text.ParseException: Unparseable date: "10-十一月-1995"
	at java.text.DateFormat.parse(DateFormat.java:366) ~[na:1.8.0_65]
	at com.ibm.janusgraph.utils.importer.util.BatchHelper.convertDate(BatchHelper.java:65) ~[janusgraph-utils-0.0.1-SNAPSHOT.jar:na]
	at com.ibm.janusgraph.utils.importer.util.BatchHelper.convertPropertyValue(BatchHelper.java:74) ~[janusgraph-utils-0.0.1-SNAPSHOT.jar:na]
	at com.ibm.janusgraph.utils.importer.edge.EdgeLoaderWorker.acceptRecord(EdgeLoaderWorker.java:119) [janusgraph-utils-0.0.1-SNAPSHOT.jar:na]
	at com.ibm.janusgraph.utils.importer.edge.EdgeLoaderWorker.access$000(EdgeLoaderWorker.java:38) [janusgraph-utils-0.0.1-SNAPSHOT.jar:na]
	at com.ibm.janusgraph.utils.importer.edge.EdgeLoaderWorker$1.accept(EdgeLoaderWorker.java:156) [janusgraph-utils-0.0.1-SNAPSHOT.jar:na]
	at com.ibm.janusgraph.utils.importer.edge.EdgeLoaderWorker$1.accept(EdgeLoaderWorker.java:152) [janusgraph-utils-0.0.1-SNAPSHOT.jar:na]
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:891) [na:1.8.0_65]
```

**Comment by stevemar** [comment]
@chinhuang007 FYI ^

**Comment by zhaochl** [comment]
thanks @chinhuang007 @stevemart   I guess the date format is incompatible with my timezone that is  China UTC+8 ,I am  eager to  use JansusGraph to solve my problem , But fund so many Problems , that's real a pitty, wish JansusGraph will be more powerful and high availability. 😄

**Comment by chinhuang007** [comment]
Thanks for the comments. The date parser is a sample code extension, working only with certain date format as expected. Developers are welcome to contribute code to cover additional date formats.

**Comment by chinhuang007** [comment]
Since the sample code is not intended to cover all date formats, I am closing the issue.
